### ISSUE TITLE
ts

### ISSUE THREAD

**Issue by cazterk** [mmatongo/learn_ts#1]
You want to learn ts?

**Comment by mmatongo** [comment]
Yeah

**Comment by mmatongo** [comment]
It's Js with `types` and I like my `types`.

**Comment by cazterk** [comment]
Hahahaha I know, start with js though

**Comment by mmatongo** [comment]
I know `js` already.

I've been coding in it for months now and I've made a lot a projects from it.
I also know react and next.

**Comment by cazterk** [comment]
need help in js I guess

**Comment by mmatongo** [comment]
What do you need help with?

**Comment by cazterk** [comment]
Everything 😀

**Comment by mmatongo** [comment]
Are you struggling with something

**Comment by cazterk** [comment]
Yes

**Comment by mmatongo** [comment]
What are you struggling with?

**Comment by cazterk** [comment]
Need a solid foundation on the basics

**Comment by mmatongo** [comment]
> Need a solid foundation on the basics

codecademy

**Comment by cazterk** [comment]
Hahahaha okay might just check it out

**Comment by cazterk** [comment]
@
